### ISSUE TITLE
使用代理授權身分token進行rest api patch 時，無法修改學生密碼

### ISSUE THREAD

**Issue by liao-chianan** [leejoneshane/tpeduSSO#15]
as title

其他欄位如first name 與 seat 能夠正常修改
但密碼無法修改成功，仍然會維持舊密碼

**Comment by leejoneshane** [comment]
確實，密碼在規劃上是屬於個資授權的範圍，未經當事人授權的話是無法變更的。如果改用個資授權讓當事人登入後，再由當事人自行進行變更就沒有問題。如果要允許管理員可以變更密碼，如何把新密碼告知當事人，目前在系統上面並沒有可靠的方法！（密碼不能經由電郵傳送！同時學生也不是都有輸入電郵！）

**Comment by williamwu0220** [comment]
想請教一下，所以在功能規劃上，即便是學校管理者產生的代理授權，也不允許更改自己學校人員的密碼？

**Comment by liao-chianan** [comment]
謝謝您的回覆，既然無法直接變更密碼，請問是否可開放管理員代理授權還原密碼的rest api
因為目前這個功能也是管理員需要用到的。

**Comment by leejoneshane** [comment]
> 想請教一下，所以在功能規劃上，即便是學校管理者產生的代理授權，也不允許更改自己學校人員的密碼？

你可以設計一個修改密碼的頁面，讓使用者透過第三方介接登入後，自行修改密碼，有對應的 api 呼叫可以使用。目前可行的作法是這樣！

**Comment by leejoneshane** [comment]
> 謝謝您的回覆，既然無法直接變更密碼，請問是否可開放管理員代理授權還原密碼的rest api
> 因為目前這個功能也是管理員需要用到的。

管理員可以登入 ldap.tp.edu.tw 去幫使用者回復密碼。下次改版會有批次回復密碼功能。對應的 api 會等網頁功能設計出來後，才會提供！

**Comment by leejoneshane** [comment]
回復密碼 API 已經上線，請詳閱手冊說明！
