### ISSUE TITLE
使用代理授權身分token能查詢其他學校教師UUID

### ISSUE THREAD

**Issue by liao-chianan** [leejoneshane/tpeduSSO#16]
as title
使用自己學校的token 進行
GET https://ldap.tp.edu.tw/api/v2/school/meps/teachers

理論上權限不符合，但還是能夠查到meps的所有教師uuid

**Comment by leejoneshane** [comment]
感謝測試，已經修正！

**Comment by liao-chianan** [comment]
辛苦了，謝謝您
(速度也太快)
