### ISSUE TITLE
可否為每個單位建立獨一無二的代碼，比方用 UUID

### ISSUE THREAD

**Issue by williamwu0220** [leejoneshane/tpeduSSO#4]
我這邊因為監控系統是監控有將網路透過台智光接到市網的單位，所以我這邊有一張表，用來對應各單位，並用會計代碼作為登入的帳號。

目前 ldap.tp.edu.tw 使用的是各校的縮寫代碼，也用此代碼作為區分各個帳號歸屬於哪個單位的依據。

但以上兩種做法都會遇到問題：

1. 會計代碼會變動
2. 有些附屬單位，會計代碼會一樣，有些會不一樣
3. 各校縮寫代碼會變動 (比方市大附小改了兩次)
4. 承 3 有些附屬單位共用同一個縮寫，更甚者，可能之後還會獨立建立自己的縮寫或更改
5. 第三方網站如果要跟 ldap.tp.edu.tw 介接維運下去，各單位有一個絕對不會變動的代碼，在日後同步上就不會因為代碼異動等因素出現錯誤的問題

不知老師想法如何？

**Comment by williamwu0220** [comment]
補充，我這邊還有類似動物園等非教育單位的學校，因為有接教育網路回市網... 還有各獨立幼兒園等單位

**Comment by leejoneshane** [comment]
目前因為會計代碼是由教育部訂定，我們沒辦法掌控，所以採用自訂的系統代碼。的確，系統代碼來自各校的網域縮寫，容易有誤解，但這個系統代碼是可以透過局端網頁介面直接整批修改，請不要把它想成網域名稱。
目前的管理辦法是不允許各校自訂系統代碼，但若學校有附屬單位應該使用不同代碼進行區分，可以向教育局承辦人聯繫。舉例來說，中崙高中和中崙高中國中部就是使用不同的代碼，雖然學校的網域名稱是共用的，但不影響系統運作。這個代碼一旦確立，除非是有代碼衝突或其他原因，否則會永久使用，因此它具有唯一性。
如果還有其他建議，請再提出來一起討論！

**Comment by leejoneshane** [comment]
補充說明，事實上所有的單位在系統上都有 UUID，不過因為不方便記憶，所有沒有拿來使用。UUID 目前僅作為系統內部搜尋使用。考慮到國小學生會有自動產生預設帳號的需求，在學號的前面會冠上單位的系統代碼做區分，如果改用 UUID 會很困擾，所以應該還是會保持目前的做法！

**Comment by williamwu0220** [comment]
其實我想表達的意思是，資訊系統與系統之間的介接，應該要靠 UUID 來做同步的依據。

以第三方的網站跟 ldap.tp.edu.tw 來說，其實我們會拉一份 使用者/群組 這樣的資料，放到 local 端的資料庫，一來避免在顯示時，每次都要跟 ldap.tp.edu.tw 撈群組資料，造成速度反應緩慢，二來萬一 ldap.tp.edu.tw 發生無法連線等狀況時，還可以有個 local db 可以運作緩衝。

所以對使用者端來說，當然可以用縮寫，或是會計代碼，都可以，甚至是第三方網站若有自己的需求，也可以自行新增帳號，並把他指派到對應的單位。

但蠻希望 ldap.tp.edu.tw 那邊，對於所謂的群組（無論是否是教育單位）或甚至是使用者，最好都能提供獨一無二的 UUID （使用者其實 email 就已經有識別性了，我是說如果要統一的話），這樣在整合上，第三方網站在同步上就會有一個依據，而不會動不動就發生異常，然後又要麻煩老師這邊。:)

**Comment by leejoneshane** [comment]
如果只是要在學校資訊裡提供 UUID，是可以的！

**Comment by scrazy77** [comment]
應該就是所有的resource(學校、單位、User)都有對應的UUID，然後api介接時以UUID為依據串之後，就算名稱或是相關欄位更改都不會影響原有的介接，蠻多大系統都用類似處理方式，因為程式間串接不用管介接字串好不好識讀的問題。
