### ISSUE TITLE
初次登入會要求修改帳號與修改密碼，希望能在修改完帳號密碼後導回到登入畫面

### ISSUE THREAD

**Issue by liao-chianan** [leejoneshane/tpeduSSO#5]
目前修改預設帳號與修改預設密碼完畢後，會留在修改畫面，使用者會誤以為沒有修改成功，因而繼續不斷重複修改，希望能夠在修改帳號或者修改密碼完畢後，將使用者導回到登入畫面，避免使用者操作錯誤

**Comment by leejoneshane** [comment]
這個我會盡快改，改好再通知！

**Comment by leejoneshane** [comment]
已經改好了！

**Comment by liao-chianan** [comment]
感謝協助，剛剛測試修改預設帳號與修改預設密碼，修改完必都能夠成功導回登入畫面
