### ISSUE TITLE
登入onlinedb.tp.edu.tw 出現認證失敗(can not get profile)訊息

### ISSUE THREAD

**Issue by liao-chianan** [leejoneshane/tpeduSSO#6]
今日有老師反映，無法使用單一身分驗證登入onlinedb.tp.edu.tw ，經過實際測試，發現如果先登入ldap.tp.edu.tw，在cookie保留的情形下繼續使用單一身分驗證登入onlinedb.tp.edu.tw，就會出現認證失敗(can not get profile)的錯誤訊息。 

暫時的workaround是請老師另開chrome無痕視窗，就能夠重新輸入帳號密碼登入。

不曉得是否是onlinedb.tp.edu.tw 那邊的介接程序出現問題。還請協助確認，謝謝!

**Comment by leejoneshane** [comment]
確認此問題已經解決！
